name: CI/CD Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.12' }
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v

  build-and-push:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_demo:latest .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops_demo:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops_demo:latest ${{ secrets.DOCKER_USERNAME }}/devops_demo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/devops_demo:${{ github.sha }}
